# Generated by Django 2.2.3 on 2021-04-25 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0002_alter_annotation_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='annotation',
        ),
        migrations.DeleteModel(
            name='Annotation',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
