# Generated by Django 2.2.3 on 2021-04-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0005_auto_20210425_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='agree',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='line',
            name='total_agree',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='line',
            name='total_disagree',
            field=models.IntegerField(default=0),
        ),
    ]
