# Generated by Django 3.2 on 2021-04-25 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0007_comment_name'),
        ('annotation', '0008_auto_20210425_1805'),
    ]

    operations = [
    ]
