# Generated by Django 3.2 on 2021-04-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0009_merge_0007_comment_name_0008_auto_20210425_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='agree',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='line',
            name='total_agree',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='line',
            name='total_disagree',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
